import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./auth_management/authProvider";
import Navbar from "./components/navigation";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body>
        <AuthProvider>
  <Navbar/>
           {children}
        </AuthProvider>
        
      </body>
    </html>
  );
}
